default: &default
  adapter: postgresql
  encoding: UTF-8
  username: jayhudson

development:
  <<: *default
  database: condomaker_development


test:
  <<: *default
  database: condomaker_test
production:
  <<: *default
  database: condomaker_production
